-- return {
--   "thewatts/nostromo.nvim",
--   version = "0.0.6",
--   lazy = false,
--   priority = 1000,
--   config = function()
--     require("nostromo").setup({
--       visible_borders = true -- defaults to false, set to true to enable visible borders
--     })
--   end,
-- }
return {}
